### ISSUE TITLE
Bytes sequences of multibyte characters are wrong

### ISSUE THREAD

**Issue by Leo1003** [cryptii/cryptii#37]
I try to turn some multibyte characters into bytes using the following two bricks:
```text
Text -> Bytes
```
But finding that the order of them are reverse to the byte sequences definition of UTF-8. 
Like '¢' should be "C2 A2"
But the result in bytes view is "A2 C2"

**Comment by ffraenz** [comment]
@Leo1003 Thank you for reporting this critical bug. It turned out that conditional compression is broken in Uglify 3.4.8 (https://github.com/mishoo/UglifyJS2/issues/3278) causing unexpected execution orders and thus reverse byte sequences. I disabled conditional compression for now resolving this issue. I will trigger a deployment in the next hours.
