### ISSUE TITLE
Base64 to Hexadecimal conversion is wrong

### ISSUE THREAD

**Issue by pdeslaur** [cryptii/cryptii#4]
Take the following example:
Base 64: OFaznuSMaIw=

The correct hexadecimal result is: 3856b39ee48c688c
The application returns: 385637a4ca0c

I believe this is caused by using UTF-8 somewhere during the conversion.

**Comment by pdeslaur** [comment]
Hum - the repo seems to have moved - but the website still points to this one...

**Comment by pdeslaur** [comment]
The local version works fine - might be worth updating the online version :)

**Comment by Nommyde** [comment]
![image](https://user-images.githubusercontent.com/8957113/28138408-5b30efb2-6759-11e7-9107-972e66e90a5a.png)

**Comment by Isanderthul** [comment]
I too have found that the BASE64 -> HEX conversion is wrong. 
I ended up using this site instead: http://tomeko.net/online_tools/base64.php?lang=en

**Comment by ffraenz** [comment]
Thank you for your feedback. I was not able to fix this issue in Cryptii v3 because your binary input is not valid UTF-8 encoded text, making things complicated. As Cryptii v4 introduces a new way of handling such cases this issue has been fixed. I [added a test](https://github.com/cryptii/cryptii/blob/3119293916975503e6a51d88c2ef0d6eb1e46cfb/test/ByteEncoder.js#L46) with your example.

Try it out for yourself: https://v4.cryptii.com/base64-to-hex
