### ISSUE TITLE
Hex to Base64 gives wrong output

### ISSUE THREAD

**Issue by arapoport** [cryptii/cryptii#46]
Hi!

Hex to base64 is not working properly...

Hex input: `A1 23`
Base64 output: `6oSj`
Base64 expected output: `oSM`

Base64 should also be shorter on any number greater than FF because hex is base 16 and has fewer digits for writing a number down.

**Comment by ffraenz** [comment]
Hello @arapoport, I can't reproduce the issue you describe. I get the expected result back. Which browser did you use? Can you attach a screenshot of the pipe you composed? Thank you!

**Comment by arapoport** [comment]
I am using the web-app in Firefox 67.0: https://v2.cryptii.com/hexadecimal/base64

![image](https://user-images.githubusercontent.com/3393725/58762424-954d5400-8558-11e9-90ee-e8932c74f5a1.png)

**Comment by arapoport** [comment]
Same in Chrome. But this webapp works as expected: https://cryptii.com/pipes/base64-to-hex

**Comment by ffraenz** [comment]
You are referring to the old version of cryptii still residing under [v2.cryptii.com](https://v2.cryptii.com). The Base64 implementation has been updated significally ever since. Please use the current implementation over at https://cryptii.com/pipes/hex-to-base64. I'll add a notice to the old version to avoid confusion.

**Comment by arapoport** [comment]
Ah, ok. Just for you to know: Google lists the old version as second match on the query "hex to base64" :-)

**Comment by ffraenz** [comment]
Indeed, I noticed that the 'Hex to base64' landing page was missing on cryptii.com and hence the older version stepped into the search results. Translation methods like Pigpen cipher and Leet speak still have no counterpart in the current version, that's why v2.cryptii.com is still available and being indexed. Thank you for the report!

**Comment by arapoport** [comment]
No problem! And sorry for the confusion, I haven't noticed at first that there are multiple versions.
