### ISSUE TITLE
Enigma I is wrong

### ISSUE THREAD

**Issue by minhlong94** [cryptii/cryptii#84]
On cryptii.com, I set the config as below:
Enigma machine
Model: Enigma I
UKW B
Rotor 1: III, Position = 1, Ring = 1
Rotor 2: II, Posi = 1, Ring = 1
Rotor 3: I, Posi = 1, Ring = 1
And I checked with http://enigmaco.de/enigma/enigma.html at the same time.
Also, I used the code provided by NSA: https://github.com/NationalSecurityAgency/enigma-simulator
At the 97th character, both cryptii and enigmaco.de gave the same result, while it was different by NSA. When I checked, enigmaco.de rolled rotor 2 TWICE. I don't know if this is because of Enigma config, so I write this to you.

**Comment by ffraenz** [comment]
There is a [test case](https://github.com/cryptii/cryptii/blob/cf77b5a20564e1d992d399ec04606180ef52549f/test/Encoder/Enigma.js#L32) in this project to make sure the (seemingly odd) rotor rotation behaviour of the original Enigma I / M3 is matched by this implementation. It has been [tested on an actual Enigma machine](https://youtu.be/unw7St0azMw):

```
Model: Enigma I, Enigma M3
Rotors: I, II, III
Initial position: 13 (M), 5 (E), 21 (U)
Ring setting: 1 (A), 1 (A), 1 (A)
Reflector: UKW-B
Input: AAAAA
Expected result: GDXTZ
```

This is what the test case should look like using the Python NSA implementation ([documentation](https://github.com/NationalSecurityAgency/enigma-simulator/blob/master/MasterEnigmaCracker.ipynb)) you mentioned. The reflection rotor is hardcoded to be UKW-B and ring settings are not supported, thus the default (A, A, A) should apply.

```python
import machine as m
e = m.Enigma()
e.set_rotor_order(['I', 'II', 'III'])
e.set_rotor_position('MEU')
print(e.encipher('AAAAA'))
# Prints out "KOBQV"
```

In case I did nothing wrong configuring the library above the NSA implementation seems to be flawed as it returns `KOBQV` instead of `GDXTZ`. This may also be the reason why your test case does not match at character 97. You may file a bug report in the repository to let them check on this. Let me know if you have further questions or feedback.

**Comment by minhlong94** [comment]
Hi ffraenz, thanks for the reply.
Now I understand. To be honest, it is very odd that the Enigma rotors go like that. Since I'm trying to code an Enigma using Python, I searched high and low and none that I saw mentioned that problem. Now I have to debug it again.
Thank you, both you and Mike Koss for showing me that real Enigma. I'll file a bug to the NSA about this and ask them to check again.

**Comment by ffraenz** [comment]
When you are working on your own implementation of the Enigma machine you can always refer to the [underlying code](https://github.com/cryptii/cryptii/blob/455d6a729b469319dca6438e23c0b6a7076e09a4/src/Encoder/Enigma.js#L574) in this project. I'll close this issue for now.
