### ISSUE TITLE
Feature request: horizontal scroll bar

### ISSUE THREAD

**Issue by LottieVixen** [cryptii/cryptii#9]
a horizontal scroll bar and/or arrows to show putting your mouse to the edge of the display moves it would be nice, scroll bars a nice for accessibility also

**Comment by focusaurus** [comment]
I'd actually prefer if the stages of transformation were laid out vertically instead of horizontally. It's a much more ergonomic design for a web app as vertical scrolling is easy and reliable. Horizontal scrolling on a desktop web browser is often unpleasant or hard to do (have to hold shift and scroll on a trackpad, etc).

I'd also like to see the UI elements significantly smaller so they fit easily onto the screen.

**Comment by TooMuchBlue** [comment]
Either a horizontal scrollbar or optional vertical layout would be an improvement.  Vertical scrolling is definitely more natural for most devices and views.

**Comment by ffraenz** [comment]
Hi, there! This won't make it into the cryptii project, as of now. However, over at [ciphereditor](https://ciphereditor.com/), we introduced a 2-dimensional canvas for desktop users. Here, operations can be laid out freely. Also, scrollbars are implemented, too, to help with navigation. See #129 for more.
